globalArguments:
  - '--global.sendanonymoususage=false'
  - '--global.checknewversion=false'

additionalArguments:
  - '--serversTransport.insecureSkipVerify=true'
  - '--log.level=DEBUG'

deployment:
  enabled: true
  replicas: 1 # equal to the number of workers/agents
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        priority: 10
  websecure:
    http3:
      enabled: true
      advertisedPort: 4443
    tls:
      enabled: true
    proxyProtocol:
      trustedIPs:
        - '0.0.0.0/0'

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: true

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/use-private-ip: 'true'
    load-balancer.hetzner.cloud/hostname: lb.k8s.domain.tld
    load-balancer.hetzner.cloud/http-redirect-https: 'false'
    load-balancer.hetzner.cloud/name: k3s-lb
    load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
  labels: {}
  # spec:
  #   loadBalancerIP: 192.168.30.80 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []
