---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: CERTIFICATE_NAME_STAGING
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: TLS_STAGING_SECRET_NAME
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '*.domain.tld'
  dnsNames:
    - 'domain.tld'
    - '*.domain.tld'
    - '*.k8s.domain.tld'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: 'longhorn-system,vaultwarden,ai,ente' # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true' # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'longhorn-system,vaultwarden,ai,ente' # Control auto-reflection namespaces
